### ISSUE TITLE
Same Name and Same City

### ISSUE THREAD

**Issue by gbif-collections** [gbif/collections-duplicates#192]
List of duplicates issues created for execution on `2021-03-12T08:55:46.021` with parameters: 
- Same Name
- Same City

183 issues created: 
- [ ] #9 Chicago Academy of Sciences - Chicago
- [ ] #10 Institute of Biology - Skopje
- [ ] #11 University of the Ryukyus - Nishihara
- [ ] #12 Universidad Nacional de San Luis - San Luis
- [x] #13 Forest Products Laboratory - Madison
- [ ] #14 Universidade Federal de Pernambuco - Recife
- [x] #15 Marlborough College - Marlborough, Wiltshire
- [ ] #16 University of Bradford - Bradford
- [ ] #17 Bedford Public Library - Bedford
- [ ] #18 University of Guelph - Guelph
- [ ] #19 Anhui Agricultural University - Hefei
- [ ] #20 Mari State University - Yoshkar-Ola
- [ ] #21 Utah State University - Logan
- [ ] #22 University of Newcastle upon Tyne - Newcastle upon Tyne
- [ ] #23 Voronezh State University - Voronezh
- [ ] #24 Louisiana State University - Baton Rouge
- [ ] #25 Marmara University - Istanbul
- [ ] #26 Universidad Central de Venezuela - Caracas
- [x] #27 University of California - Davis
- [x] #28 University of Adelaide - Adelaide
- [x] #29 Chicago Academy of Sciences (duplicate of https://registry.gbif.org/institution/8759e747-e33f-46c5-b1d3-4f008295dddc) - Chicago
- [ ] #30 Royal Ontario Museum - Toronto
- [ ] #31 University of KwaZulu-Natal, Westville campus - Durban
- [ ] #32 North-West University - Potchefstroom
- [ ] #33 Agriculture and Agri-Food Canada - Ottawa
- [ ] #34 Archbold Biological Station - Venus
- [x] #35 Lushan Botanical Garden - Lushan
- [x] #36 Duke University - Durham
- [x] #37 Australian National Herbarium - Canberra
- [x] #38 Forestry and Rural Developmen Department - Winnipeg
- [ ] #39 Universidad Nacional Mayor de San Marcos - Lima
- [ ] #40 Yale University - New Haven
- [x] #41 University of Cape Town - Cape Town
- [x] #42 Université de Liège - Liège
- [ ] #43 University of Wyoming - Laramie
- [ ] #44 California Academy of Sciences - San Francisco
- [ ] #45 Yunnan University - Kunming
- [x] #46 Osaka Museum of Natural History - Osaka
- [ ] #47 University of Stellenbosch - Stellenbosch
- [x] #48 University of Minnesota - St. Paul
- [x] #49 Universitat de València - València
- [ ] #50 New Mexico State University - Las Cruces
- [ ] #51 Harvard University - Cambridge
- [ ] #52 Anhui Normal University - Wuhu
- [ ] #53 San Diego State University - San Diego
- [x] #54 Natural History Museum of Los Angeles County - Los Angeles
- [ ] #55 Naturalis - Leiden
- [x] #56 Universitat de Barcelona - Barcelona
- [ ] #57 Universidad de la República - Montevideo
- [ ] #58 Academy of Natural Sciences - Philadelphia
- [ ] #59 Laurentian Forestry Centre, Canadian Forest Service - Québec
- [ ] #60 University of Nevada - Reno
- [x] #61 Institute of Botany of the National Academy of Sciences of Armenia - Yerevan 63
- [ ] #62 Yerevan State University - Yerevan
- [ ] #63 Tasmanian Museum and Art Gallery - Hobart
- [ ] #64 Universidade Federal de Ouro Prêto - Ouro Prêto
- [ ] #65 Broward College - Davie
- [ ] #66 Università degli Studi di Napoli Federico II - Portici
- [ ] #67 Texas A&M University - College Station
- [ ] #68 University of Basel - Basel
- [ ] #69 Hacettepe University - Ankara
- [ ] #70 Indian Agricultural Research Institute - New Delhi
- [ ] #71 University of Hull - Kingston upon Hull
- [ ] #72 University of Latvia - Riga
- [ ] #73 Jardin botanique de Montréal - Montréal
- [ ] #74 Grant Museum of Zoology and Comparative Anatomy UCL - London
- [ ] #75 Université Paul Sabatier - Toulouse
- [ ] #76 Universidad de Granada - Granada
- [ ] #77 Bristol Museum and Art Gallery - Bristol, Avon
- [ ] #78 Northern Forestry Centre, Canadian Forest Service - Edmonton
- [ ] #79 Santa Barbara Museum of Natural History - Santa Barbara
- [ ] #80 Washington State University - Pullman
- [ ] #81 Virginia Military Institute - Lexington
- [ ] #82 Kagoshima University - Kagoshima
- [ ] #83 Warwickshire Museum - Warwick
- [ ] #84 University of Bristol - Bristol, Avon
- [ ] #85 University of Zagreb - Zagreb
- [ ] #86 Universidad Nacional Autónoma de México - Mexico City
- [x] #87 Smithsonian Institution, National Museum of Natural History - Washington
- [ ] #88 Hokkaido University Museum - Sapporo
- [ ] #89 Northwest Normal University - Lanzhou
- [ ] #90 University of Nottingham - Nottingham
- [ ] #91 Museum für Naturkunde - Berlin
- [ ] #92 Sonoma State University - Rohnert Park
- [x] #93 Okayama University of Science - Okayama
- [x] #94 Universidad de Salamanca - Salamanca
- [ ] #95 University of Southern California - Los Angeles
- [x] #96 Universidad de Sevilla - Sevilla
- [x] #97 Australian National University - Canberra
- [x] #98 University of Wales - Bangor
- [ ] #99 South China Agricultural University - Guangzhou
- [x] #100 Leeds Museums and Galleries - Leeds
- [ ] #101 Colorado State University - Fort Collins
- [ ] #102 Southern Illinois University - Carbondale
- [ ] #103 University of Birmingham - Birmingham
- [ ] #104 Pontifícia Universidade Católica do Paraná - Curitiba
- [ ] #105 Science Museum of Minnesota - Saint Paul
- [ ] #106 National Taiwan University - Taipei
- [ ] #107 Hebei Agricultural University - Baoding
- [ ] #108 Smithsonian Tropical Research Institute - Balboa
- [ ] #109 Anadolu University - Eskisehir
- [ ] #110 Universidad Austral de Chile - Valdivia
- [ ] #111 Sichuan Agricultural University - Yaan
- [ ] #112 Sichuan Academy of Traditional Chinese Medicine and Pharmacy - Nanchuan
- [ ] #113 Universidad Autónoma de Baja California - Ensenada
- [ ] #114 University of Baghdad - Baghdad
- [ ] #115 inatura Erlebnis Naturschau GmbH - Dornbirn
- [ ] #116 Università di Sassari - Sassari
- [ ] #117 University of California - Berkeley
- [ ] #118 National Chung Hsing University - Taichung
- [ ] #119 Universidad de Buenos Aires - Buenos Aires
- [ ] #120 Museo Nacional de Historia Natural - Montevideo
- [ ] #121 Transvaal Museum - Pretoria
- [ ] #122 Agricultural University of Athens - Athens
- [ ] #123 Guangxi University - Nanning
- [ ] #124 Sam Noble Oklahoma Museum of Natural History - Norman
- [ ] #125 University of Alabama - Tuscaloosa
- [ ] #126 Wroclaw University - Wroclaw
- [ ] #127 Asenovgrad Museum - Asenovgrad
- [ ] #128 Royal British Columbia Museum - Victoria
- [ ] #129 Universidad Nacional del Sur - Bahía Blanca
- [ ] #130 Guizhou Agricultural College - Guiyang
- [ ] #131 Ibaraki University - Mito
- [ ] #132 University of Alberta - Edmonton
- [ ] #133 Fundação Estadual de Pesquisa Agropecuária - Porto Alegre
- [x] #134 National and Kapodistrian University of Athens - Athens
- [ ] #135 Universidade Federal do Oeste do Pará - Santarém
- [x] #136 University of Connecticut Biodiversity Research Collections - Storrs
- [ ] #137 University of Oxford - Oxford
- [ ] #138 Milwaukee Public Museum - Milwaukee
- [x] #139 Universidade de São Paulo - São Paulo
- [ ] #140 Universidade Federal dos Vales do Jequitinhonha e Mucuri - Diamantina
- [ ] #141 Shrewsbury School - Shrewsbury
- [ ] #142 University of Istanbul - Istanbul
- [ ] #143 Southwest Agricultural University - Chongqing
- [ ] #144 Estonian University of Life Sciences - Tartu
- [ ] #145 Universidad de Magallanes - Punta Arenas
- [ ] #146 University of Craiova - Craiova
- [ ] #147 Rocky Mountain Research Station, USDA Forest Service - Flagstaff
- [ ] #148 Universidad de Chile - Santiago
- [ ] #149 Universidad de San Carlos de Guatemala - Guatemala City
- [ ] #150 University of Mosul - Mosul
- [ ] #151 Shenyang Agricultural University - Shenyang
- [x] #152 California Department of Food and Agriculture - Sacramento
- [ ] #153 Field Museum of Natural History - Chicago
- [x] #154 Universität Basel - Basel
- [ ] #155 Denver Botanic Gardens - Denver
- [ ] #156 Universidad de Los Andes - Mérida
- [ ] #157 Universidad Nacional de La Plata - La Plata
- [x] #158 Bundesamt für Naturschutz - Bonn
- [ ] #159 Università degli Studi di Milano - Milano
- [ ] #160 Xinjiang University - Urumqi
- [x] #161 University of Aberdeen - Aberdeen
- [ ] #162 Tohoku University - Sendai
- [ ] #163 United States National Arboretum, USDA-ARS - Washington
- [ ] #164 Cornell University - Ithaca
- [x] #165 University of Reading - Reading
- [ ] #166 Bulgarian Academy of Sciences - Sofia
- [ ] #167 University of Idaho - Moscow
- [ ] #168 University of Saskatchewan - Saskatoon
- [ ] #169 King Saud University - Riyadh
- [ ] #170 Museo de La Plata - La Plata
- [ ] #171 Universidade Federal Rural do Rio de Janeiro - Seropédica
- [ ] #172 Banaras Hindu University - Varanasi
- [x] #173 Université Laval - Québec
- [ ] #174 Guizhou Normal University - Guiyang
- [ ] #175 Universidad Central - Quito
- [ ] #176 University of Arizona - Tucson
- [x] #177 Université de la Réunion - Sainte-Clotilde
- [ ] #178 Universidad Veracruzana - Xalapa
- [ ] #179 Purdue University - West Lafayette
- [x] #180 University of Tsukuba - Tsukuba
- [ ] #181 University of Tokyo - Tokyo
- [ ] #182 Michigan Technological University - Houghton
- [ ] #183 University of Texas at Austin - Austin
- [ ] #184 University of Turku - Turku
- [x] #185 Universidade Federal de Minas Gerais - Belo Horizonte
- [ ] #186 Oregon State University - Corvallis
- [x] #187 University of the Philippines at Los Baños - College
- [ ] #188 University of Notre Dame - Notre Dame
- [x] #189 Gezira Research Station - Wad Medani
- [ ] #190 University of Tennessee at Chattanooga - Chattanooga
- [x] #191 University of Delaware - Newark
